---

- hosts: localhost
  tasks:
  - git:
      repo: 'https://github.com/harishchanderdalal/ansible.git'
      dest: /home/deployment/
      refspec: '+refs/pull/*:refs/heads/*'
      version: "{{BRANCH}}"
