---

- hosts: localhost
  tasks:
    - name: Git Clone Frontend REPO
      git: >
        repo: 'https://github.com/harishchanderdalal/AWS.git'
        dest: /home/deployment
        refspec: '+refs/pull/*:refs/heads/*'
